import React, { createContext, useContext, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const api = async (path, options = {}) => {
  const token = localStorage.getItem('abes-token');
  const response = await fetch('/api' + path, {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...(token ? { Authorization: 'Bearer ' + token } : {}),
      ...options.headers,
    },
  });
  if (response.status === 204) return null;
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || 'Something went wrong.');
  return data;
};
const AuthContext = createContext();
const useAuth = () => useContext(AuthContext);
const navigate = path => { window.history.pushState({}, '', path); window.dispatchEvent(new Event('popstate')); };
function Brand() { return <a className="brand" href="/" onClick={e => { e.preventDefault(); navigate('/'); }}><i>A</i>ABES <b>PULSE</b></a>; }
function Header({ minimal=false }) { const { user, logout } = useAuth(); return <header className="top"><Brand />{!minimal && <nav><a href="/#events">Discover</a><a href="/#spotlight">Campus life</a>{user ? <><a href={user.role === 'student' ? '/student' : '/organizer'} onClick={e => { e.preventDefault(); navigate(e.currentTarget.getAttribute('href')); }}>My portal</a><button className="text-button" onClick={logout}>Sign out</button></> : <button className="nav-button" onClick={() => navigate('/login')}>Sign in <span>→</span></button>}</nav>}</header>; }
function EventCard({ event, saved, onSave }) { return <article className="event-card"><div className="event-image" style={{ backgroundImage:`linear-gradient(0deg, rgba(9,10,22,.55), rgba(9,10,22,.04)), url('${event.image}')` }}><small>{event.type}</small><button aria-label="Save event" className={saved ? 'saved' : ''} onClick={() => onSave(event.id)}>{saved ? '♥' : '♡'}</button></div><div className="event-body"><time>{event.date}</time><h3>{event.title}</h3><p>{event.description}</p><div><span>⌖ {event.venue}</span><button className="link-button" onClick={() => navigate(`/events/${event.id}`)}>Details →</button></div></div></article>; }
function Home() { const { user } = useAuth(); const [events,setEvents]=useState([]), [saved,setSaved]=useState([]), [filter,setFilter]=useState('all'), [query,setQuery]=useState('');
  const fetchEvents=()=>api('/events').then(setEvents).catch(console.error); useEffect(()=>{fetchEvents(); if(user) api('/me/saved').then(setSaved).catch(()=>{});},[user]);
  const toggleSave=async id=>{if(!user){navigate('/login');return;} const was=saved.includes(id); try{await api(`/me/saved/${id}`,{method:was?'DELETE':'PUT'});setSaved(items=>was?items.filter(x=>x!==id):[...items,id]);}catch(error){alert(error.message);}};
  const visible=events.filter(event => (filter==='all'||event.category===filter) && `${event.title} ${event.description} ${event.venue}`.toLowerCase().includes(query.toLowerCase()));
  return <><Header/><main><section className="hero"><div><p className="eyebrow">● ABES CAMPUS · LIVE NOW</p><h1>Find your <em>next</em><br/>campus moment.</h1><p className="hero-copy">From all-night hackathons to quiet sunrise runs, ABES Pulse puts the best of campus life in one place.</p><div className="actions"><button className="primary" onClick={()=>document.querySelector('#events').scrollIntoView({behavior:'smooth'})}>Explore events ↓</button><button className="link-button light" onClick={()=>navigate('/login')}>{user ? 'Open my portal' : 'Join ABES Pulse'} ↗</button></div><div className="numbers"><div><b>{events.length}+</b><span>upcoming events</span></div><div><b>12</b><span>student communities</span></div><div><b>1</b><span>campus, together</span></div></div></div><div className="feature" style={{backgroundImage:"linear-gradient(0deg,rgba(9,10,22,.85),rgba(9,10,22,0)),url('https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1100&q=85')"}}><small>LIVE THIS WEEK</small><h2>Vibrance ’26</h2><p>Music · Dance · Culture</p></div></section><div className="ticker">NEXT UP · CODESTORM · VIBRANCE ’26 · STARTUP SPRINT · ROBOWARS · SUNDAY RUN · OPEN MIC</div><section id="events" className="discover"><p className="eyebrow purple">● DISCOVER WHAT’S HAPPENING</p><div className="section-title"><h2>Find your thing.</h2><p>Every event here is made by people on your campus, for people on your campus.</p></div><div className="finder"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search events, clubs, or interests"/><div>{['all','tech','culture','sports','career'].map(item=><button key={item} className={filter===item?'active':''} onClick={()=>setFilter(item)}>{item==='all'?'All events':item}</button>)}</div></div><div className="event-grid">{visible.length ? visible.map(event=><EventCard key={event.id} event={event} saved={saved.includes(event.id)} onSave={toggleSave}/>) : <p className="empty">No events match your search.</p>}</div></section><section id="spotlight" className="spotlight"><div><p className="eyebrow">● SPOTLIGHT</p><h2>Made for the moments you remember.</h2><p>ABES Pulse is the simple way to find people, possibilities, and your place beyond the classroom.</p></div><button className="primary" onClick={()=>navigate('/register')}>Create your account →</button></section></main><Footer/></>; }
function EventPage({ id }) { const [event,setEvent]=useState(null); const { user }=useAuth(); useEffect(()=>{api(`/events/${id}`).then(setEvent).catch(()=>navigate('/'));},[id]); if(!event)return <div className="page"><Header minimal/><p>Loading event…</p></div>; return <><div className="page"><Header minimal/><button className="back" onClick={()=>navigate('/')}>← All events</button><section className="event-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(7,8,18,.92),rgba(7,8,18,.15)),url('${event.image}')`}}><div><p className="eyebrow">{event.type}</p><h1>{event.title}</h1><p>{event.description}</p><div className="quick"><span>{event.date}</span><span>{event.time}</span><span>{event.venue}</span></div></div></section><section className="detail-layout"><article><p className="eyebrow">WHY YOU SHOULD BE THERE</p><h2>More than an event. A campus moment.</h2><p className="long-copy">{event.purpose}</p><h2>Show up. Level up.</h2><div className="perks">{event.perks.map(perk=><div key={perk}><span>✦</span><b>{perk}</b><p>Included with your event experience.</p></div>)}</div></article><aside className="essentials"><h3>Event essentials</h3><p><small>DATE</small>{event.date}</p><p><small>TIME</small>{event.time}</p><p><small>VENUE</small>{event.venue}</p><p><small>ENTRY</small>{event.entry}</p><button className="primary full" onClick={()=>user?.role==='student'?navigate(`/events/${event.id}/register`):navigate('/login')}>Register for this event →</button></aside></section></div><Footer/></>; }
function AuthPage({ register=false }) { const [role,setRole]=useState('student'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false); const { login }=useAuth(); const submit=async e=>{e.preventDefault();setBusy(true);setMessage('');const form=new FormData(e.currentTarget);try{const data=await api(`/auth/${register?'register':'login'}`,{method:'POST',body:JSON.stringify(Object.fromEntries(form))});login(data);navigate(data.user.role==='student'?'/student':'/organizer');}catch(error){setMessage(error.message);}finally{setBusy(false);}}; return <main className="auth"><Brand/><section><div className="auth-intro"><p className="eyebrow">CAMPUS ACCESS</p><h1>{register?'Your next chapter starts here.':'Make your next move.'}</h1><p>Discover the best of ABES campus life, or publish an experience worth showing up for.</p></div><form onSubmit={submit} className="auth-card"><h2>{register?'Create an account.':`${role==='student'?'Student':'Organizer'} sign in.`}</h2><p>{register?'Choose your access and get started.':'Choose your workspace and continue with your account.'}</p>{!register&&<div className="role-pills"><button type="button" className={role==='student'?'active':''} onClick={()=>setRole('student')}>Student portal<small>Discover & register</small></button><button type="button" className={role==='organizer'?'active':''} onClick={()=>setRole('organizer')}>Organizer portal<small>Publish & manage</small></button></div>}{register&&<label>Full name<input name="name" required autoComplete="name"/></label>}<input type="hidden" name="role" value={role}/><label>Email<input name="email" type="email" required autoComplete="username"/></label><label>Password<input name="password" type="password" minLength="4" required autoComplete={register?'new-password':'current-password'}/></label><button className="primary full" disabled={busy}>{busy?'Please wait…':register?'Create account →':`Sign in as ${role} →`}</button>{message&&<p className="form-error">{message}</p>}<p className="switch">{register?'Already have an account?':'New to ABES Pulse?'} <button type="button" onClick={()=>navigate(register?'/login':'/register')}>{register?'Sign in':'Create an account'}</button></p></form></section></main>; }
function RegisterEvent({ id }) { const [event,setEvent]=useState(null),[message,setMessage]=useState(''); const { user }=useAuth(); useEffect(()=>{ if(!user)navigate('/login'); else api(`/events/${id}`).then(setEvent);},[id,user]); const submit=async e=>{e.preventDefault();try{await api('/registrations',{method:'POST',body:JSON.stringify({eventId:id,...Object.fromEntries(new FormData(e.currentTarget))})});setMessage('You’re confirmed! Your registration is now in your student portal.'); e.currentTarget.reset();}catch(error){setMessage(error.message);}}; return <main className="registration"><Header minimal/><section><div className="registration-info"><p className="eyebrow">EVENT REGISTRATION</p><h1>{event?.title || 'Save your spot.'}</h1><p>Confirmation and important details are saved to your signed-in account.</p><p>✓ Instant confirmation<br/>✓ Event reminders<br/>✓ Easy check-in</p></div><form onSubmit={submit}><h2>Let’s get you in.</h2><label>Full name<input name="name" defaultValue={user?.name} required/></label><label>Year<select name="year" required><option value="">Select your year</option><option>1st year</option><option>2nd year</option><option>3rd year</option><option>4th year</option></select></label><label>Branch<input name="branch" required placeholder="e.g. Computer Science"/></label><button className="primary full">Confirm my registration →</button>{message&&<p className={message.startsWith('You')?'success':'form-error'}>{message}</p>}</form></section></main>; }
function StudentPortal() { const { user,logout }=useAuth(); const [tab,setTab]=useState('registrations'),[events,setEvents]=useState([]),[registrations,setRegistrations]=useState([]),[saved,setSaved]=useState([]); useEffect(()=>{if(!user||user.role!=='student'){navigate('/login');return;}Promise.all([api('/events'),api('/me/registrations'),api('/me/saved')]).then(([a,b,c])=>{setEvents(a);setRegistrations(b);setSaved(c);});},[user]);const items=tab==='registrations'?registrations.map(item=>item.event):tab==='saved'?events.filter(item=>saved.includes(item.id)):events;return <div className="portal"><Header minimal/><button className="logout" onClick={logout}>Sign out</button><p className="eyebrow">STUDENT PORTAL</p><h1>Your campus,<br/><em>in one place.</em></h1><p>Keep your registrations and saved events separate from every other ABES Pulse account.</p><div className="tabs">{[['registrations','My registrations'],['published','New on campus'],['saved','Saved events']].map(([key,label])=><button className={tab===key?'active':''} onClick={()=>setTab(key)} key={key}>{label}</button>)}</div><section className="portal-box"><h2>{tab==='registrations'?'My registrations':tab==='saved'?'Saved events':'New on campus'}</h2>{items.length?items.map(event=><div className="portal-item" key={event.id}><span>{event.date}</span><div><b>{event.title}</b><small>⌖ {event.venue}</small></div><button className="link-button" onClick={()=>navigate(`/events/${event.id}`)}>View →</button></div>):<p className="empty">Nothing here yet. Explore events and come back anytime.</p>}<button className="primary" onClick={()=>navigate('/')}>Discover all events →</button></section></div>; }
function OrganizerPortal() { const { user,logout }=useAuth(); const [dashboard,setDashboard]=useState({events:[],registrations:0}),[message,setMessage]=useState('');const reload=()=>api('/organizer/dashboard').then(setDashboard).catch(()=>navigate('/login'));useEffect(()=>{if(!user||user.role!=='organizer')navigate('/login');else reload();},[user]);const submit=async e=>{e.preventDefault();try{const event=await api('/events',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});setMessage(`${event.title} is now live for students.`);e.currentTarget.reset();reload();}catch(error){setMessage(error.message);}};const remove=async id=>{await api(`/events/${id}`,{method:'DELETE'});reload();};return <div className="portal"><Header minimal/><button className="logout" onClick={logout}>Sign out</button><p className="eyebrow">ORGANIZER WORKSPACE</p><h1>Publish events.<br/><em>Bring campus together.</em></h1><p>Create a complete listing that becomes visible in the student discovery feed immediately.</p><div className="stats"><div><b>{dashboard.events.length}</b><small>published events</small></div><div><b>{dashboard.registrations}</b><small>student registrations</small></div><div><b>1 min</b><small>to publish a listing</small></div></div><section className="organizer-grid"><form className="portal-box publish-form" onSubmit={submit}><h2>Publish an event</h2><label>Event name<input name="title" required placeholder="e.g. Design Jam 2026"/></label><label>Category<select name="category"><option value="tech">Tech & build</option><option value="culture">Culture</option><option value="sports">Sports</option><option value="career">Career</option></select></label><label>Date<input name="date" required placeholder="12 November 2026"/></label><label>Time<input name="time" required placeholder="10:00 AM – 4:00 PM"/></label><label>Venue<input name="venue" required placeholder="Block A auditorium"/></label><label>Purpose<textarea name="purpose" required placeholder="What will students experience and why should they attend?"/></label><label>Benefits<input name="benefits" placeholder="Certificate, goodies, mentorship"/></label><button className="primary">Publish to ABES Pulse →</button>{message&&<p className="success">{message}</p>}</form><aside className="portal-box"><h2>Your published events</h2>{dashboard.events.length?dashboard.events.map(event=><div className="portal-item" key={event.id}><div><b>{event.title}</b><small>{event.date} · {event.venue}</small></div><button className="danger" onClick={()=>remove(event.id)}>Remove</button></div>):<p className="empty">No events published yet.</p>}</aside></section></div>; }
function Footer(){return <footer>ABES Engineering College · ABES Pulse · Campus experiences, made easy.</footer>}
function App(){const [location,setLocation]=useState(window.location.pathname);const [session,setSession]=useState(()=>{try{return JSON.parse(localStorage.getItem('abes-user'));}catch{return null;}});useEffect(()=>{const update=()=>setLocation(window.location.pathname);addEventListener('popstate',update);return()=>removeEventListener('popstate',update);},[]);const login=data=>{localStorage.setItem('abes-token',data.token);localStorage.setItem('abes-user',JSON.stringify(data.user));setSession(data.user);};const logout=()=>{localStorage.removeItem('abes-token');localStorage.removeItem('abes-user');setSession(null);navigate('/');};const content=location==='/'?<Home/>:location==='/login'?<AuthPage/>:location==='/register'?<AuthPage register/>:location==='/student'?<StudentPortal/>:location==='/organizer'?<OrganizerPortal/>:location.match(/^\/events\/([^/]+)\/register$/)?<RegisterEvent id={location.split('/')[2]}/>:location.match(/^\/events\/([^/]+)$/)?<EventPage id={location.split('/')[2]}/>:<Home/>;return <AuthContext.Provider value={{user:session,login,logout}}>{content}</AuthContext.Provider>}
createRoot(document.getElementById('root')).render(<App/>);
